# echo "Welcome to the library database!"
# echo "Please select from one of the following options:"
# echo "1. check out a copy"
# echo "2. check in a copy"
# echo "3. Add a book or copy of book"
# echo "4. Remove a copy or book"
# echo "5. Register a new library member"
# echo "6. Query information"
# echo ""
# echo "Enter the information for a checkout: copy_id, member_id, libarian_id"
# echo "<values entered>"
# echo "Successful! Book has been checked out."
# echo ""
# echo "Enter the information for a check in: copy_id, member_id, libarian_id"
# echo "<values entered>"
# echo "Successful! Book has been checked in."
# echo ""
# echo "Add a new book/copy to system: title, author_id, number_of_copies"
# echo "<values entered>"
# echo "Successful! Book(s) has been added."
# echo ""
# echo "Delete a copy from the system: copy_id"
# echo "<values entered>"
# echo "Successful! Copy has been deleted."
# echo ""
# echo "Register new library member: name, address, number"
# echo "<values entered>"
# echo "Successful! Member has been created."

echo "Please select from one of the following query options:"
echo "1. See if there is a copy of a book at a specific location"
echo "2. How many books a member currently has checked out"
echo "3. Find available copies of a specific book"
echo "4. Find books by a specific author"
echo "5. Find authors that has most books in system"
echo "6. Return customer who has checked out the most books overall"
echo "7. How many books per library"
echo "8. cancel"

echo ""
echo "Enter values to see if a copy exists at a location: book_id, library_id"
echo "<values entered>"
echo "True: there is a copy of this book here."
echo ""
echo "Enter values to see how many books this member has checked out: member_id"
echo "<values entered>"
echo "Member has 5 books out."
echo ""
echo "Find libraries where this book is available: book_id"
echo "<values entered>"
echo "It is available at Branch A and C."
echo ""
echo "Enter values to see what books are written by this author: author_id"
echo "<values entered>"
echo "Author has written these books: ....."
echo ""
echo "Which author has most books in system?"
echo "Dr Suess has the most books: 55."
echo ""
echo "Which customer has checkout out the most books overall?"
echo "Shawn Bowers has checked out 1058 books."
echo ""
echo "How many books per library?"
echo "Library A: 34 books."
echo "Library B: 100 books."
echo "Library C: 8970 books."
